### ISSUE TITLE
Recording Bug Clicks - Clicked links not registering. 

### ISSUE THREAD

**Issue by mweiss427** [MakerDAO/MIPs#443]
The click number is not incremented when right-clicked. 

![image](https://user-images.githubusercontent.com/22085759/149990083-c825285d-9cd7-4b63-b321-cd92bb979afc.png)

![image](https://user-images.githubusercontent.com/22085759/149990249-b5ff28eb-fe54-4d91-912a-bc1b98a234e2.png)

**Comment by Geoge1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14164218/

**Comment by ghost** [comment]
Closing this as this is not the relevant repo for this report.

(Apologies for the time delay since this was submitted for any action)
