### ISSUE TITLE
url mangled?

### ISSUE THREAD

**Issue by jpritikin** [MakerDAO/MIPs#605]
On the MIPs portal, looking at https://mips.makerdao.com/mips/details/MIP40c3SP41

I see "MKR incentives have been determined based on the [Program discussed here](https://github.com/makerdao/mips/blob/master/MIP40/MIP40c3-Subproposals/MIP40c3-SP41.md). This is a 3-year vesting plan with 1-year cliff vest."

The URL seems to mismatch what is in the GIT repo,

"MKR incentives have been determined based on the [Program discussed here](https://forum.makerdao.com/t/pre-mip-discussion-an-alternative-mkr-compensation-plan/8000). This is a 3-year vesting plan with 1-year cliff vest."

**Comment by ghost** [comment]
I am happy to report that this has been belatedly fixed here: https://github.com/makerdao/makerdao-mips/pull/790
